add_newline = false
format = """
$character\
$directory\
$git_branch"""
right_format = """$battery"""

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[directory]
truncation_length = 1

[git_branch]
format = '[git:\($branch\) ]($style)'
style = 'blue'

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"
format = '[$symbol ]($style)'

[[battery.display]]
threshold = 40
style = 'bold red'
